### PR TITLE
fix: type defs for stream upload methods

### PR DESCRIPTION
**Pull request by nsine**
All stream upload methods return stream itself, not promise.
This PR fixes typings for them

### CODE REVIEW

**Comment by nsine** [comment]
@strausr I think using `ts-stream` is not necessary. Adding `@types/node` would be enough for running tests

**Comment by nsine** [comment]
can smb also look at ci? it fails in both of my PRs: this one and https://github.com/cloudinary/cloudinary_npm/pull/335
what would be the reason?

**Comment by asisayag2** [comment]
@nsine, thanks for the PR. 
We will look into it as soon as possible and this will include making sure the CI is passing.

**Comment by nsine** [comment]
@strausr hm
but i already did it month ago 😅
https://github.com/cloudinary/cloudinary_npm/pull/336/commits/41bc0ef210d3ecc0e6fa54de420d5eac2a546115

**Pull request merged**
