### PR TITLE
Keep getting Missing public_ids when deleting

### PR DESCRIPTION
**Pull request by Artmobile**
delete_resources expects public_ids not public_ids[]

### CODE REVIEW

**Comment by TalLevAmi** [comment]
There was an issue with node >= 0.12 admin API failing non-GET requests. Please try again with master.

**Comment by Artmobile** [comment]
Tal, I reinstalled your module with npm install cloudinary. Same error occurs when trying to delete a resource even with node 0.11

From what we saw you have an error in line 61 in your api.coffee:

call_api("delete", uri, _.extend({"public_ids[]": public_ids}

**public_ids[]** should be **public_ids**

My pull request made everything work

**Comment by TalLevAmi** [comment]
public_ids[] is correct. We have just released version 1.2.0 of the npm. Can you please try with it?

**Comment by Artmobile** [comment]
Yes, it worked now! 

Thank you

**Pull request closed without merging**
